# Generated by Django 5.2 on 2026-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienImmobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('surface', models.IntegerField(default=0)),
                ('nombre_pieces', models.IntegerField(default=0)),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('terrain', 'Terrain')], default='maison', max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('vendu_loue', 'Vendu/Loué'), ('negociation', 'En négociation')], default='disponible', max_length=20)),
                ('adresse', models.CharField(blank=True, default='', max_length=200)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('code_postal', models.CharField(blank=True, default='', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_biens/')),
                ('legende', models.CharField(blank=True, default='', max_length=200)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='biens.bienimmobilier')),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mandat', models.CharField(default='simple', max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biens.bienimmobilier')),
            ],
        ),
    ]
