# Generated by Django 5.2 on 2026-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bail', models.CharField(choices=[('vide', 'Vide'), ('meuble', 'Meublé')], default='vide', max_length=20)),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('bien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biens.bienimmobilier')),
                ('locataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_etat', models.DateField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='location.bail')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(default='virement', max_length=20)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='location.bail')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='etat_lieux/')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='location.etatdeslieux')),
            ],
        ),
        migrations.CreateModel(
            name='QuittanceLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='', max_length=50)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='location.bail')),
            ],
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('date_signalement', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='location.bail')),
            ],
        ),
    ]
