# Generated by Django 5.2 on 2026-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteVitrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='marketing.campagnemarketing')),
            ],
        ),
        migrations.CreateModel(
            name='DestinataireEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinataires', to='marketing.campagnemarketing')),
            ],
        ),
        migrations.CreateModel(
            name='EmailMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('corps', models.TextField(blank=True, default='')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='marketing.campagnemarketing')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationSociale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='marketing.campagnemarketing')),
            ],
        ),
    ]
