# Generated by Django 5.2 on 2026-08-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('budget_depense', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pourcentage_avancement', models.IntegerField(default=0)),
                ('etat_chantier', models.CharField(choices=[('planifie', 'Planifié'), ('preparation', 'Préparation'), ('en_cours', 'En cours'), ('finition', 'Finition'), ('termine', 'Terminé'), ('livre', 'Livré'), ('en_retard', 'En retard')], default='planifie', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
