# Generated by Django 5.2 on 2026-08-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_categorie', models.CharField(choices=[('recette', 'Recette'), ('depense', 'Dépense')], default='depense', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, default='', max_length=100)),
                ('banque', models.CharField(blank=True, default='', max_length=200)),
                ('type_compte', models.CharField(choices=[('courant', 'Courant'), ('epargne', 'Epargne')], default='courant', max_length=20)),
                ('solde_initial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default='FAC-0001', max_length=50)),
                ('type_facture', models.CharField(choices=[('honoraire', 'Honoraires'), ('frais_agence', 'Frais agence'), ('autre', 'Autre')], default='honoraire', max_length=30)),
                ('date_emission', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_operation', models.DateField(blank=True, null=True)),
                ('date_valeur', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(default='virement', max_length=30)),
                ('libelle', models.CharField(default='', max_length=200)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.categorie')),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite.comptebancaire')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='comptabilite.facture')),
            ],
        ),
    ]
